#!/usr/bin/env python3
"""Test script for Linear issue creation.

Usage:
    # Set environment variable first
    export LINEAR_API_KEY="lin_api_..."

    # Run test
    python test_linear_create_issue.py <team_id> <title>

Example:
    python test_linear_create_issue.py "a1b2c3d4-..." "Test issue from TurboWrap"
"""

import asyncio
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

from turbowrap.review.integrations.linear import LinearClient


async def test_create_issue(team_id: str, title: str):
    """Test Linear issue creation."""

    print("🔧 Creating Linear issue...")
    print(f"   Team ID: {team_id}")
    print(f"   Title: {title}\n")

    # Create client
    try:
        client = LinearClient()
        print("✅ LinearClient initialized\n")
    except ValueError as e:
        print(f"❌ Failed to initialize client: {e}")
        print("💡 Set LINEAR_API_KEY environment variable")
        return

    # Create issue
    description = """## Test Issue

This is a test issue created from **TurboWrap** to verify the `create_issue()` method.

### Test Details

- Created via: Python script
- Method: `LinearClient.create_issue()`
- Purpose: Integration test

### Expected Behavior

This issue should:
- [x] Appear in Linear workspace
- [x] Have this description
- [x] Be assigned to the specified team

---

*Generated by TurboWrap test suite*
"""

    try:
        print("⏳ Creating issue on Linear...\n")
        issue = await client.create_issue(
            team_id=team_id,
            title=title,
            description=description,
            priority=0,  # No priority
        )

        print("=" * 80)
        print("✅ ISSUE CREATED SUCCESSFULLY")
        print("=" * 80)
        print(f"ID:          {issue['id']}")
        print(f"Identifier:  {issue['identifier']}")
        print(f"Title:       {issue['title']}")
        print(f"URL:         {issue['url']}")
        print(f"Priority:    {issue['priority']}")
        print(f"State:       {issue['state']['name']} ({issue['state']['type']})")
        print(f"Team:        {issue['team']['name']} ({issue['team']['key']})")
        if issue.get('assignee'):
            print(f"Assignee:    {issue['assignee']['name']} ({issue['assignee']['email']})")
        print(f"Created At:  {issue['createdAt']}")
        print("=" * 80)
        print(f"\n🔗 View issue: {issue['url']}")

    except RuntimeError as e:
        print(f"❌ Linear API error: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()


async def test_get_workflow_states(team_id: str):
    """Get workflow states to help with testing."""

    print(f"\n📋 Fetching workflow states for team {team_id}...\n")

    try:
        client = LinearClient()
        states = await client.get_workflow_states(team_id)

        print("Available workflow states:")
        print("-" * 60)
        for state in states:
            print(f"  {state['name']:20} | ID: {state['id']} | Type: {state['type']}")
        print("-" * 60)
        print("\n💡 Use these state IDs when creating issues with custom states")

    except Exception as e:
        print(f"❌ Failed to fetch states: {e}")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python test_linear_create_issue.py <team_id> <title>")
        print("\nTo get workflow states:")
        print("  python test_linear_create_issue.py <team_id> --states")
        print("\nExample:")
        print('  python test_linear_create_issue.py "a1b2c3d4-..." "Test Issue"')
        sys.exit(1)

    team_id = sys.argv[1]

    # Check if user wants to see states
    if len(sys.argv) > 2 and sys.argv[2] == "--states":
        asyncio.run(test_get_workflow_states(team_id))
    else:
        title = " ".join(sys.argv[2:])
        asyncio.run(test_create_issue(team_id, title))
