"""initial schema

Revision ID: 1e870cf19a8b
Revises:
Create Date: 2025-12-26 10:05:07.451397+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e870cf19a8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("local_path", sa.String(length=512), nullable=False),
        sa.Column("default_branch", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("repo_type", sa.String(length=50), nullable=True),
        sa.Column("project_name", sa.String(length=255), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("workspace_path", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repositories_deleted_at"), "repositories", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_repositories_project_name"), "repositories", ["project_name"], unique=False
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.String(length=1), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "cli_chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column("cli_type", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("agent_name", sa.String(length=100), nullable=True),
        sa.Column("thinking_enabled", sa.Boolean(), nullable=True),
        sa.Column("thinking_budget", sa.Integer(), nullable=True),
        sa.Column("reasoning_enabled", sa.Boolean(), nullable=True),
        sa.Column("mcp_servers", sa.JSON(), nullable=True),
        sa.Column("process_pid", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("total_messages", sa.Integer(), nullable=True),
        sa.Column("total_tokens_in", sa.Integer(), nullable=True),
        sa.Column("total_tokens_out", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cli_chat_sessions_repo", "cli_chat_sessions", ["repository_id"], unique=False
    )
    op.create_index("idx_cli_chat_sessions_status", "cli_chat_sessions", ["status"], unique=False)
    op.create_index("idx_cli_chat_sessions_type", "cli_chat_sessions", ["cli_type"], unique=False)
    op.create_index(
        op.f("ix_cli_chat_sessions_deleted_at"), "cli_chat_sessions", ["deleted_at"], unique=False
    )
    op.create_table(
        "repository_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_repo_id", sa.String(length=36), nullable=False),
        sa.Column("target_repo_id", sa.String(length=36), nullable=False),
        sa.Column("link_type", sa.String(length=50), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_repo_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_repo_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_repository_links_source", "repository_links", ["source_repo_id"], unique=False
    )
    op.create_index(
        "idx_repository_links_target", "repository_links", ["target_repo_id"], unique=False
    )
    op.create_index("idx_repository_links_type", "repository_links", ["link_type"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("progress_message", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tasks_repository", "tasks", ["repository_id"], unique=False)
    op.create_index("idx_tasks_status", "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_deleted_at"), "tasks", ["deleted_at"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_agent_runs_task", "agent_runs", ["task_id"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_sessions_deleted_at"), "chat_sessions", ["deleted_at"], unique=False
    )
    op.create_table(
        "cli_chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_thinking", sa.Boolean(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("agent_used", sa.String(length=100), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["cli_chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cli_chat_messages_created", "cli_chat_messages", ["created_at"], unique=False
    )
    op.create_index("idx_cli_chat_messages_role", "cli_chat_messages", ["role"], unique=False)
    op.create_index(
        "idx_cli_chat_messages_session", "cli_chat_messages", ["session_id"], unique=False
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("issue_code", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("rule", sa.String(length=100), nullable=True),
        sa.Column("file", sa.String(length=500), nullable=False),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("current_code", sa.Text(), nullable=True),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("references", sa.JSON(), nullable=True),
        sa.Column("flagged_by", sa.JSON(), nullable=True),
        sa.Column("estimated_effort", sa.Integer(), nullable=True),
        sa.Column("estimated_files_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("fix_code", sa.Text(), nullable=True),
        sa.Column("fix_explanation", sa.Text(), nullable=True),
        sa.Column("fix_files_modified", sa.JSON(), nullable=True),
        sa.Column("fix_commit_sha", sa.String(length=40), nullable=True),
        sa.Column("fix_branch", sa.String(length=100), nullable=True),
        sa.Column("fix_session_id", sa.String(length=36), nullable=True),
        sa.Column("fixed_at", sa.DateTime(), nullable=True),
        sa.Column("fixed_by", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_issues_category", "issues", ["category"], unique=False)
    op.create_index("idx_issues_file", "issues", ["file"], unique=False)
    op.create_index("idx_issues_repository", "issues", ["repository_id"], unique=False)
    op.create_index("idx_issues_severity", "issues", ["severity"], unique=False)
    op.create_index("idx_issues_status", "issues", ["status"], unique=False)
    op.create_index("idx_issues_task", "issues", ["task_id"], unique=False)
    op.create_index(op.f("ix_issues_deleted_at"), "issues", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_issues_fix_session_id"), "issues", ["fix_session_id"], unique=False)
    op.create_index(op.f("ix_issues_is_active"), "issues", ["is_active"], unique=False)
    op.create_table(
        "linear_issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("linear_id", sa.String(length=100), nullable=False),
        sa.Column("linear_identifier", sa.String(length=50), nullable=False),
        sa.Column("linear_url", sa.String(length=512), nullable=False),
        sa.Column("linear_team_id", sa.String(length=100), nullable=False),
        sa.Column("linear_team_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("improved_description", sa.Text(), nullable=True),
        sa.Column("assignee_id", sa.String(length=100), nullable=True),
        sa.Column("assignee_name", sa.String(length=255), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column("turbowrap_state", sa.String(length=50), nullable=False),
        sa.Column("linear_state_id", sa.String(length=100), nullable=True),
        sa.Column("linear_state_name", sa.String(length=100), nullable=True),
        sa.Column("linear_state_triage_id", sa.String(length=100), nullable=True),
        sa.Column("linear_state_todo_id", sa.String(length=100), nullable=True),
        sa.Column("linear_state_inprogress_id", sa.String(length=100), nullable=True),
        sa.Column("linear_state_inreview_id", sa.String(length=100), nullable=True),
        sa.Column("linear_state_done_id", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("analysis_summary", sa.Text(), nullable=True),
        sa.Column("analysis_comment_id", sa.String(length=100), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.Column("analyzed_by", sa.String(length=100), nullable=True),
        sa.Column("user_answers", sa.JSON(), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("fix_commit_sha", sa.String(length=40), nullable=True),
        sa.Column("fix_branch", sa.String(length=100), nullable=True),
        sa.Column("fix_explanation", sa.Text(), nullable=True),
        sa.Column("fix_files_modified", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_linear_issues_active", "linear_issues", ["is_active"], unique=False)
    op.create_index(
        "idx_linear_issues_identifier", "linear_issues", ["linear_identifier"], unique=False
    )
    op.create_index("idx_linear_issues_linear_id", "linear_issues", ["linear_id"], unique=False)
    op.create_index("idx_linear_issues_state", "linear_issues", ["turbowrap_state"], unique=False)
    op.create_index("idx_linear_issues_team", "linear_issues", ["linear_team_id"], unique=False)
    op.create_index(
        op.f("ix_linear_issues_deleted_at"), "linear_issues", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_linear_issues_is_active"), "linear_issues", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_linear_issues_linear_id"), "linear_issues", ["linear_id"], unique=True)
    op.create_index(
        op.f("ix_linear_issues_linear_identifier"),
        "linear_issues",
        ["linear_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_linear_issues_linear_team_id"), "linear_issues", ["linear_team_id"], unique=False
    )
    op.create_index(
        op.f("ix_linear_issues_turbowrap_state"), "linear_issues", ["turbowrap_state"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_chat_messages_session", "chat_messages", ["session_id"], unique=False)
    op.create_table(
        "linear_issue_repository_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("linear_issue_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("link_source", sa.String(length=50), nullable=False),
        sa.Column("source_label", sa.String(length=100), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["linear_issue_id"],
            ["linear_issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("linear_issue_id", "repository_id", name="uq_linear_issue_repo"),
    )
    op.create_index(
        "idx_linear_repo_links_issue",
        "linear_issue_repository_links",
        ["linear_issue_id"],
        unique=False,
    )
    op.create_index(
        "idx_linear_repo_links_repo",
        "linear_issue_repository_links",
        ["repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_linear_repo_links_repo", table_name="linear_issue_repository_links")
    op.drop_index("idx_linear_repo_links_issue", table_name="linear_issue_repository_links")
    op.drop_table("linear_issue_repository_links")
    op.drop_index("idx_chat_messages_session", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_linear_issues_turbowrap_state"), table_name="linear_issues")
    op.drop_index(op.f("ix_linear_issues_linear_team_id"), table_name="linear_issues")
    op.drop_index(op.f("ix_linear_issues_linear_identifier"), table_name="linear_issues")
    op.drop_index(op.f("ix_linear_issues_linear_id"), table_name="linear_issues")
    op.drop_index(op.f("ix_linear_issues_is_active"), table_name="linear_issues")
    op.drop_index(op.f("ix_linear_issues_deleted_at"), table_name="linear_issues")
    op.drop_index("idx_linear_issues_team", table_name="linear_issues")
    op.drop_index("idx_linear_issues_state", table_name="linear_issues")
    op.drop_index("idx_linear_issues_linear_id", table_name="linear_issues")
    op.drop_index("idx_linear_issues_identifier", table_name="linear_issues")
    op.drop_index("idx_linear_issues_active", table_name="linear_issues")
    op.drop_table("linear_issues")
    op.drop_index(op.f("ix_issues_is_active"), table_name="issues")
    op.drop_index(op.f("ix_issues_fix_session_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_deleted_at"), table_name="issues")
    op.drop_index("idx_issues_task", table_name="issues")
    op.drop_index("idx_issues_status", table_name="issues")
    op.drop_index("idx_issues_severity", table_name="issues")
    op.drop_index("idx_issues_repository", table_name="issues")
    op.drop_index("idx_issues_file", table_name="issues")
    op.drop_index("idx_issues_category", table_name="issues")
    op.drop_table("issues")
    op.drop_index("idx_cli_chat_messages_session", table_name="cli_chat_messages")
    op.drop_index("idx_cli_chat_messages_role", table_name="cli_chat_messages")
    op.drop_index("idx_cli_chat_messages_created", table_name="cli_chat_messages")
    op.drop_table("cli_chat_messages")
    op.drop_index(op.f("ix_chat_sessions_deleted_at"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index("idx_agent_runs_task", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_tasks_deleted_at"), table_name="tasks")
    op.drop_index("idx_tasks_status", table_name="tasks")
    op.drop_index("idx_tasks_repository", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("idx_repository_links_type", table_name="repository_links")
    op.drop_index("idx_repository_links_target", table_name="repository_links")
    op.drop_index("idx_repository_links_source", table_name="repository_links")
    op.drop_table("repository_links")
    op.drop_index(op.f("ix_cli_chat_sessions_deleted_at"), table_name="cli_chat_sessions")
    op.drop_index("idx_cli_chat_sessions_type", table_name="cli_chat_sessions")
    op.drop_index("idx_cli_chat_sessions_status", table_name="cli_chat_sessions")
    op.drop_index("idx_cli_chat_sessions_repo", table_name="cli_chat_sessions")
    op.drop_table("cli_chat_sessions")
    op.drop_table("settings")
    op.drop_index(op.f("ix_repositories_project_name"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_deleted_at"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###
